import Head from 'next/head'
import { useState } from 'react'
import React from 'react'
import { Loading, Header } from '../components'
import { Box, Button, useColorMode } from "@chakra-ui/react"
import { useContract } from "@thirdweb-dev/react"

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode()
  const { contract, isLoading } = useContract(
    "0xA669C184917fD4977047A10090898E6B60850B25"
  );

  if (isLoading) { return <Loading /> }
  return (
    <>
      <Head>
        <title>Lucky Tickets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto%3Aital%2Cwght%400%2C100%3B0%2C300%3B0%2C400%3B0%2C500%3B0%2C700%3B0%2C900%3B1%2C100%3B1%2C300%3B1%2C400%3B1%2C500%3B1%2C700%3B1%2C900&display=swap"
        />
      </Head>
      <Header />
{/*       <Button onClick={toggleColorMode} colorScheme="teal">
        Toggle color mode
      </Button> */}
    </>
  );
}
